#!/usr/bin/env python3
"""tokio 第三阶段翻译：补译所有 OWN untranslated docblock（含字节模式 + CRLF 处理）。"""
import os

BASE = r'D:/Administrator/Documents/Code/rust_doc_all/tokio'

# 句子级翻译 (en, zh) - 长字符串优先
SENTENCE_PAIRS = [
    # ===== attr.main =====
    ('Note that Tokio specific options will be lost. Currently, this only applies to kill_on_drop.', '请注意，tokio 特有的选项将丢失。目前，这仅影响 kill_on_drop。'),
    ('Builder methods are provided to change these defaults and', '提供了 Builder 方法来修改这些默认值并'),
    ('Wraps a type in both <code>BufWriter</code> and <code>BufReader</code>.', '将一个类型同时包装为 <code>BufWriter</code> 与 <code>BufReader</code>。'),
    ('Wraps a type in both BufWriter and BufReader.', '将一个类型同时包装为 BufWriter 与 BufReader。'),
    ('Creates a new <code>BufReader</code> with a default buffer capacity. The default is currently 8 KB, but may change in the future.', '使用默认缓冲容量创建 <code>BufReader</code>。当前默认为 8 KB，但未来可能变化。'),
    ('Creates a new <code>BufReader</code> with a default buffer capacity. The default is currently 8 KB,', '使用默认缓冲容量创建 <code>BufReader</code>。当前默认为 8 KB，'),
    ('Creates a new <code>BufWriter</code> with a default buffer capacity. The default is currently 8 KB, but may change in the future.', '使用默认缓冲容量创建 <code>BufWriter</code>。当前默认为 8 KB，但未来可能变化。'),
    ('Creates a new <code>BufWriter</code> with a default buffer capacity. The default is currently 8 KB,', '使用默认缓冲容量创建 <code>BufWriter</code>。当前默认为 8 KB，'),
    ('Creates a new <code>BufStream</code> with the default buffer capacities for the wrapped <code>BufReader</code> and <code>BufWriter</code>.', '使用包装的 <code>BufReader</code> 与 <code>BufWriter</code> 的默认缓冲容量创建 <code>BufStream</code>。'),
    ('Creates a new BufStream with the default buffer capacities for the wrapped BufReader and BufWriter.', '使用包装的 BufReader 与 BufWriter 的默认缓冲容量创建 BufStream。'),
    ('Creates a new <code>BufStream</code> with the specified <code>BufReader</code> capacity and <code>BufWriter</code> capacity.', '使用指定的 <code>BufReader</code> 与 <code>BufWriter</code> 容量创建 <code>BufStream</code>。'),
    ('Creates a <code>BufStream</code> with the specified <code>BufReader</code> capacity and <code>BufWriter</code> capacity. See the documentation for those types and <code>BufStream</code> for details.', '使用指定的 <code>BufReader</code> 与 <code>BufWriter</code> 容量创建 <code>BufStream</code>。详见相关类型与 <code>BufStream</code> 的文档。'),
    ('Creates a new <code>AsyncRead</code> instance that chains this stream with another.', '创建一个新的 <code>AsyncRead</code> 实例，将此流与另一个流链接起来。'),
    ('Creates a new AsyncRead instance that chains this stream with', '创建一个新的 AsyncRead 实例，将此流与'),
    ('Gets a reference to the underlying I/O object.', '获取底层 I/O 对象的引用。'),
    ('Gets a mutable reference to the underlying I/O object.', '获取底层 I/O 对象的可变引用。'),
    ('It is inadvisable to directly read from the underlying I/O object.', '不建议直接读取底层 I/O 对象。'),
    ('Gets a pinned mutable reference to the underlying I/O object.', '获取底层 I/O 对象的 pinned 可变引用。'),
    ('Consumes this BufStream, returning the underlying I/O object.', '消费此 BufStream，返回底层 I/O 对象。'),
    ('Gets a reference to the underlying reader.', '获取底层读取器的引用。'),
    ('Gets a reference to the underlying writer.', '获取底层写入器的引用。'),
    ('Gets a mutable reference to the underlying reader.', '获取底层读取器的可变引用。'),
    ('Gets a mutable reference to the underlying writer.', '获取底层写入器的可变引用。'),
    ('Gets a pinned mutable reference to the underlying reader.', '获取底层读取器的 pinned 可变引用。'),
    ('Gets a pinned mutable reference to the underlying writer.', '获取底层写入器的 pinned 可变引用。'),
    ('Consumes this BufReader, returning the underlying reader.', '消费此 BufReader，返回底层读取器。'),
    ('Consumes this BufWriter, returning the underlying writer.', '消费此 BufWriter，返回底层写入器。'),
    ('Consumes this Take, returning the wrapped reader.', '消费此 Take，返回被包装的读取器。'),
    ('Gets mutable references to the underlying readers in this <code>Chain</code>.', '获取此 <code>Chain</code> 中底层读取器的可变引用。'),
    ('Gets mutable references to the underlying readers in this Chain.', '获取此 Chain 中底层读取器的可变引用。'),
    ('Gets pinned mutable references to the underlying readers in this <code>Chain</code>.', '获取此 <code>Chain</code> 中底层读取器的 pinned 可变引用。'),
    ('Gets pinned mutable references to the underlying readers in this Chain.', '获取此 Chain 中底层读取器的 pinned 可变引用。'),
    ('Consuming the <code>Chain</code>, returning the wrapped readers.', '消费此 <code>Chain</code>，返回被包装的读取器。'),
    ('Consuming the Chain, returning the wrapped readers.', '消费此 Chain，返回被包装的读取器。'),
    ('Care should be taken to avoid modifying the internal I/O state of the underlying readers as doing so may corrupt the internal state of this <code>Chain</code>.', '请注意避免修改底层读取器的内部 I/O 状态，否则可能损坏此 <code>Chain</code> 的内部状态。'),
    ('Care should be taken to avoid modifying the internal I/O state of the', '请注意避免修改底层 I/O 状态，'),
    ('Sets the number of bytes that can be read before this instance will return EOF.', '设置此实例返回 EOF 之前可读取的字节数。'),
    ('Sets the number of bytes that can be read before this instance will', '设置此实例返回 EOF 之前可读取的字节数。'),
    ('Returns the maximum number of bytes that can be read.', '返回可读取的最大字节数。'),
    ('Returns the remaining number of bytes that can be read before this instance will return EOF.', '返回此实例返回 EOF 之前还可以读取的剩余字节数。'),
    ('Returns the remaining number of bytes that can be', '返回还可以读取的剩余字节数。'),
    ('Note: This instance may reach EOF after reading fewer bytes than indicated by this method if the underlying reader does not provide enough data.', '注意：如果底层读取器没有提供足够的数据，此实例可能在读取的字节少于本方法指示的数量时到达 EOF。'),
    ('This instance may reach EOF after reading fewer bytes than indicated by this method if the underlying reader does not provide enough data.', '如果底层读取器没有提供足够的数据，此实例可能在读取的字节少于本方法指示的数量时到达 EOF。'),
    ('This instance may reach EOF after reading fewer bytes than indicated by', '此实例可能在读取的字节少于指示的数量时到达 EOF，'),
    ('Splits this <code>Join</code> back into its <code>AsyncRead</code> and <code>AsyncWrite</code> components.', '将此 <code>Join</code> 拆回 <code>AsyncRead</code> 与 <code>AsyncWrite</code> 两个组件。'),
    ('Splits this Join back into its AsyncRead and AsyncWrite', '将此 Join 拆回 AsyncRead 与 AsyncWrite'),
    ('Returning a reference to the inner reader.', '返回内部读取器的引用。'),
    ('Returning a reference to the inner writer.', '返回内部写入器的引用。'),
    ('Returns the inner reader.', '返回内部读取器。'),
    ('Returns a mutable reference to the inner reader.', '返回内部读取器的可变引用。'),
    ('Returns a pinned mutable reference to the inner reader.', '返回内部读取器的 pinned 可变引用。'),
    ('Returns the next line in the stream.', '返回流中的下一行。'),
    ('Polls for the next line in the stream.', '轮询流中的下一行。'),
    ('Returns the next segment in the stream.', '返回流中的下一段。'),
    ('Polls for the next segment in the stream.', '轮询流中的下一段。'),
    ('Unwraps this <code>Lines&lt;R&gt;</code>, returning the underlying reader.', '解包此 <code>Lines&lt;R&gt;</code>，返回底层读取器。'),
    ('Unwraps this Lines&lt;R&gt;, returning the underlying reader.', '解包此 Lines&lt;R&gt;，返回底层读取器。'),

    # ===== io/DuplexStream/Empty/Repeat =====
    ('The <code>DuplexStream</code> struct allows you to read and write from a bidirectional stream.', '<code>DuplexStream</code> 结构体允许你从一个双向流中读写。'),
    ('The <code>Empty</code> struct allows you to create an empty reader.', '<code>Empty</code> 结构体允许你创建一个空读取器。'),
    ('The <code>Repeat</code> struct allows you to create a reader that repeats a single byte value infinitely.', '<code>Repeat</code> 结构体允许你创建一个无限重复单个字节值的读取器。'),
    ('The <code>Sink</code> struct allows you to write a stream of values.', '<code>Sink</code> 结构体允许你写一个值流。'),
    ('The <code>Split</code> struct allows you to split a bidirectional stream into separate read and write halves.', '<code>Split</code> 结构体允许你将一个双向流拆分为独立的读、写两半。'),

    # ===== io/stdin/stdout/stderr =====
    ('The <code>stdin</code> handle is best used for non-interactive uses, such as when a file is piped into the application.', '<code>stdin</code> handle 最适合非交互场景，例如将文件通过管道输入应用。'),
    ('Reads a line from standard input.', '从标准输入读取一行。'),
    ('The line does not include the trailing newline character.', '读取的行不包含末尾的换行符。'),
    ('Concurrent writes to stdout must be executed with care: Only individual writes to this <code>AsyncWrite</code> are guaranteed to be intact.', '对 stdout 的并发写入必须谨慎执行：只有向此 <code>AsyncWrite</code> 的单个写入才保证是完整的。'),
    ('Concurrent writes to stderr must be executed with care: Only individual writes to this <code>AsyncWrite</code> are guaranteed to be intact.', '对 stderr 的并发写入必须谨慎执行：只有向此 <code>AsyncWrite</code> 的单个写入才保证是完整的。'),

    # ===== ReadHalf / WriteHalf =====
    ('Checks if this <code>ReadHalf</code> and some <code>WriteHalf</code> were split from the same stream.', '检查此 <code>ReadHalf</code> 与某个 <code>WriteHalf</code> 是否是从同一个流拆分而来。'),
    ('Checks if this <code>WriteHalf</code> and some <code>ReadHalf</code> were split from the same stream.', '检查此 <code>WriteHalf</code> 与某个 <code>ReadHalf</code> 是否是从同一个流拆分而来。'),
    ('Checks if this ReadHalf and some WriteHalf were split from the same', '检查此 ReadHalf 与某个 WriteHalf 是否是从同一个流拆分而来。'),
    ('Checks if this WriteHalf and some ReadHalf were split from the same', '检查此 WriteHalf 与某个 ReadHalf 是否是从同一个流拆分而来。'),
    ('Reunites with a previously split <code>WriteHalf</code>.', '与之前拆分的 <code>WriteHalf</code> 重新合并。'),
    ('If this <code>ReadHalf</code> and the given <code>WriteHalf</code> do not originate from the same split operation this method will panic.', '若此 <code>ReadHalf</code> 与给定的 <code>WriteHalf</code> 不是来自同一次拆分操作，此方法将 panic。'),
    ('If this ReadHalf and the given WriteHalf do not originate from the', '若此 ReadHalf 与给定的 WriteHalf 不是来自同一次拆分操作，'),
    ('This can be checked ahead of time by calling <code>is_pair_of()</code>.', '可通过调用 <code>is_pair_of()</code> 提前检查。'),
    ('This can be checked ahead of time by calling is_pair_of().', '可通过调用 is_pair_of() 提前检查。'),
    ('This can be checked ahead of time with the <code>peer_addr</code> method.', '可通过 <code>peer_addr</code> 方法预先检查。'),

    # ===== Take/Chain =====
    ('Sets the number of bytes that can be read before this instance will\nreturn EOF. This is the same as constructing a new <code>Take</code> instance, so\nthe amount of bytes read and the previous limit value don\'t matter.',
     '设置此实例返回 EOF 之前可读取的字节数。这与构造一个新的 <code>Take</code> 实例等价，因此之前已读取的字节数与先前的限制值无关。'),
    ('Sets the number of bytes that can be read before this instance will return EOF. This is the same as constructing a new Take instance, so',
     '设置此实例返回 EOF 之前可读取的字节数。这与构造一个新的 Take 实例等价，因此'),
    ('Getting a reference to the underlying reader.', '获取底层读取器的引用。'),
    ('Getting a mutable reference to the underlying reader. Care should be\ntaken to avoid modifying the internal I/O state of the underlying reader as\ndoing so may corrupt the internal limit of this <code>Take</code>.',
     '获取底层读取器的可变引用。请注意避免修改底层读取器的内部 I/O 状态，否则可能损坏此 <code>Take</code> 的内部限制。'),
    ('Getting a mutable reference to the underlying reader. Care should be taken to avoid modifying the internal I/O state of the underlying reader as',
     '获取底层读取器的可变引用。请注意避免修改底层读取器的内部 I/O 状态，'),
    ('Getting a pinned mutable reference to the underlying reader. Care should be taken to avoid modifying the internal I/O state of the underlying reader as',
     '获取底层读取器的 pinned 可变引用。请注意避免修改底层读取器的内部 I/O 状态，'),
    ('Consuming the <code>Take</code>, returning the wrapped reader.', '消费此 <code>Take</code>，返回被包装的读取器。'),
    ('Consuming the Take, returning the wrapped reader.', '消费此 Take，返回被包装的读取器。'),

    # ===== copy/copy_bidirectional/copy_buf =====
    ('Asynchronously copies the entire contents of a reader into a writer.', '异步将一个读取器的全部内容复制到写入器。'),
    ('This function returns a future that will continuously read data from\nreader and then write it into writer in a streaming fashion until\nreader returns EOF.',
     '此函数返回一个 Future，它会持续从 reader 读取数据，然后以流式方式写入 writer，直到 reader 返回 EOF。'),
    ('This function returns a future that will continuously read data from reader and then write it into writer in a streaming fashion until',
     '此函数返回一个 Future，它会持续从 reader 读取数据，然后以流式方式写入 writer，直到'),
    ('On success, the total number of bytes that were copied from reader to\nwriter is returned.',
     '成功时返回从 reader 复制到 writer 的总字节数。'),
    ('A copy of bytes is currently buffered inside the function. To improve\nperformance, this buffer may be larger than the amount of data needed to\nfill <code>writer</code>\'s capacity. So if <code>writer</code> writes slowly, the buffer may grow\nunbounded.',
     '字节副本当前在函数内部缓冲。为提升性能，该缓冲可能大于填满 <code>writer</code> 容量所需的数据量。因此，若 <code>writer</code> 写入较慢，缓冲可能无界增长。'),
    ('A copy of bytes is currently buffered inside the function. To improve performance, this buffer may be larger than the amount of data needed to fill',
     '字节副本当前在函数内部缓冲。为提升性能，该缓冲可能大于填满'),
    ('This is an asynchronous version of <a href="https://doc.rust-lang.org/1.95.0/std/io/fn.copy.html" title="fn std::io::copy"><code>std::io::copy</code></a>.', '这是 <a href="https://doc.rust-lang.org/1.95.0/std/io/fn.copy.html" title="fn std::io::copy"><code>std::io::copy</code></a> 的异步版本。'),
    ('The <code>reader</code> and <code>writer</code> are copied until EOF is reached on <code>reader</code>, or an error occurs.', '持续复制 <code>reader</code> 与 <code>writer</code>，直到 <code>reader</code> 到达 EOF 或发生错误。'),
    ('Copies data in both directions between <code>a</code> and <code>b</code>.', '在 <code>a</code> 与 <code>b</code> 之间双向复制数据。'),
    ('Asynchronously copies data between two streams, in both directions.', '在两个流之间双向异步复制数据。'),
    ('Returns a future that resolves when copying in either direction finishes.', '返回一个 Future，当任一方向的复制完成时解析。'),
    ('If an error occurs during the copy in either direction, the future resolves to that error.', '若任一方向的复制过程中出错，Future 解析为该错误。'),
    ('Copies data from <code>reader</code> into <code>buf</code> until <code>reader</code> reaches EOF.', '将数据从 <code>reader</code> 复制到 <code>buf</code>，直到 <code>reader</code> 到达 EOF。'),
    ('On success, the number of bytes copied is returned.', '成功时返回已复制的字节数。'),

    # ===== empty/repeat/simplex/sink =====
    ('This is an asynchronous version of <a href="https://doc.rust-lang.org/1.95.0/std/io/struct.Empty.html" title="struct std::io::Empty"><code>std::io::Empty</code></a>.', '这是 <a href="https://doc.rust-lang.org/1.95.0/std/io/struct.Empty.html" title="struct std::io::Empty"><code>std::io::Empty</code></a> 的异步版本。'),
    ('This is an asynchronous version of <a href="https://doc.rust-lang.org/1.95.0/std/io/struct.Repeat.html" title="struct std::io::Repeat"><code>std::io::Repeat</code></a>.', '这是 <a href="https://doc.rust-lang.org/1.95.0/std/io/struct.Repeat.html" title="struct std::io::Repeat"><code>std::io::Repeat</code></a> 的异步版本。'),
    ('Creates a bidirectional in-memory pipe backed by a buffer of size\n<code>max_buf_size</code>. Reads/writes from the returned <code>ReadHalf</code>/<code>WriteHalf</code>\nwill be buffered.',
     '创建一个由大小为 <code>max_buf_size</code> 的缓冲支持的双向内存管道。从返回的 <code>ReadHalf</code>/<code>WriteHalf</code> 进行的读写都会被缓冲。'),
    ('Creating a unidirectional buffer that acts like an in-memory pipe. To\ncreate a split version with separate reader and writer you can use\nsimplex function.',
     '创建一个像内存管道一样的单向缓冲。要创建读写分离的拆分版本，请使用 simplex 函数。'),
    ('Creating a unidirectional buffer that acts like in memory pipe. To create split', '创建一个像内存管道一样的单向缓冲。要创建读写分离的拆分版本，请使用 simplex 函数。'),
    ('The <code>max_buf_size</code> argument is the maximum amount of bytes that can be stored in the buffer.', '<code>max_buf_size</code> 参数是缓冲能存储的最大字节数。'),
    ('The max_buf_size argument is the maximum amount of bytes that can be', 'max_buf_size 参数是缓冲能存储的最大字节数。'),

    # ===== fs/ =====
    ('Returns the canonical, absolute form of a path with all intermediate\ncomponents normalized and symbolic links resolved.',
     '返回路径的规范化绝对形式，所有中间组件均被规范化，且符号链接被解析。'),
    ('Returns the canonical, absolute form of a path with all intermediate components normalized and symbolic links resolved.',
     '返回路径的规范化绝对形式，所有中间组件均被规范化，且符号链接被解析。'),
    ('This function currently corresponds to the <code>realpath</code> function on Unix and the <code>CreateFile</code> and <code>GetFinalPathNameByHandle</code> functions on Windows. Note that, this may change in the future.',
     '此函数目前对应于 Unix 上的 <code>realpath</code> 与 Windows 上的 <code>CreateFile</code> 和 <code>GetFinalPathNameByHandle</code>。未来可能发生变化。'),
    ('This function currently corresponds to the realpath function on Unix and the CreateFile and GetFinalPathNameByHandle functions on Windows. Note that, this may change in the future.',
     '此函数目前对应于 Unix 上的 realpath 与 Windows 上的 CreateFile 和 GetFinalPathNameByHandle。未来可能发生变化。'),
    ('Copies the contents of one file to another. This function will also\ncopy the permission bits of the original file to the destination file.',
     '将一个文件的内容复制到另一个文件。此函数还会将原始文件的权限位复制到目标文件。'),
    ('Copies the contents of one file to another. This function will also copy the permission bits of the original file to the destination file.',
     '将一个文件的内容复制到另一个文件。此函数还会将原始文件的权限位复制到目标文件。'),
    ('On success, the total number of bytes copied is returned and it is\nequal to the length of the <code>to</code> file.',
     '成功时返回复制的总字节数，等于 <code>to</code> 文件的长度。'),
    ('On success, the total number of bytes copied is returned and it is equal to the length of the <code>to</code> file.',
     '成功时返回复制的总字节数，等于 <code>to</code> 文件的长度。'),
    ('Creates a new, empty directory at the provided path.', '在指定路径创建一个新的空目录。'),
    ('This function currently corresponds to the <code>mkdir</code> function on Unix and the <code>CreateDirectory</code> function on Windows. Note that, this may change in the future.',
     '此函数目前对应于 Unix 上的 <code>mkdir</code> 与 Windows 上的 <code>CreateDirectory</code>。未来可能发生变化。'),
    ('This function currently corresponds to the mkdir function on Unix and the CreateDirectory function on Windows. Note that, this may change in the future.',
     '此函数目前对应于 Unix 上的 mkdir 与 Windows 上的 CreateDirectory。未来可能发生变化。'),
    ('Recursively create a directory and all of its parent components if they are missing.',
     '递归创建目录及其所有缺失的父组件。'),
    ('Creates a new hard link on the filesystem.', '在文件系统上创建一个新的硬链接。'),
    ('The <code>dst</code> path will be a link pointing to the <code>original</code> path.', '<code>dst</code> 路径将成为指向 <code>original</code> 路径的链接。'),
    ('The dst path will be a link pointing to the original path.', 'dst 路径将成为指向 original 路径的链接。'),
    ('Returns the metadata for a file or directory.', '返回文件或目录的元数据。'),
    ('Asynchronously read the entire contents of a file into a bytes vector.', '异步将文件的全部内容读入字节向量。'),
    ('Returns a future of <a href="https://doc.rust-lang.org/1.95.0/std/io/error/type.Result.html" title="type std::io::error::Result"><code>Result</code></a>. On success, contains the file contents as a bytes vector.',
     '返回 <a href="https://doc.rust-lang.org/1.95.0/std/io/error/type.Result.html" title="type std::io::error::Result"><code>Result</code></a> 的 Future。成功时包含以字节向量表示的文件内容。'),
    ('Returns a future of <a href="https://doc.rust-lang.org/1.95.0/std/io/error/type.Result.html" title="type std::io::error::Result"><code>Result</code></a>. On success, contains the file contents as a string.',
     '返回 <a href="https://doc.rust-lang.org/1.95.0/std/io/error/type.Result.html" title="type std::io::error::Result"><code>Result</code></a> 的 Future。成功时包含以字符串表示的文件内容。'),
    ('Returns a future of <code>Option</code>. <code>Some</code> when the path exists, <code>None</code> when it does not.', '返回 <code>Option</code> 的 Future。路径存在时为 <code>Some</code>，不存在时为 <code>None</code>。'),
    ('This function currently corresponds to the <code>remove</code> function on Unix and the <code>DeleteFile</code> and <code>RemoveDirectory</code> functions on Windows.',
     '此函数目前对应于 Unix 上的 <code>remove</code> 与 Windows 上的 <code>DeleteFile</code> 和 <code>RemoveDirectory</code>。'),
    ('This function currently corresponds to the remove function on Unix and the DeleteFile and RemoveDirectory functions on Windows.',
     '此函数目前对应于 Unix 上的 remove 与 Windows 上的 DeleteFile 和 RemoveDirectory。'),
    ('Removes a file from the filesystem.', '从文件系统删除一个文件。'),
    ('Removes a directory at the provided path.', '删除指定路径的目录。'),
    ('Removes a directory at this path, after removing all its contents.', '递归删除该路径的目录及其全部内容。'),
    ('Renames a file or directory to a new name, replacing the original file\nif <code>to</code> already exists.',
     '将文件或目录重命名为新名称；若 <code>to</code> 已存在则覆盖。'),
    ('Renames a file or directory to a new name, replacing the original file if <code>to</code> already exists.',
     '将文件或目录重命名为新名称；若 <code>to</code> 已存在则覆盖。'),
    ('This will not work if the new name is on a different mount point.', '若新名称在不同的挂载点上，此操作将失败。'),
    ('Changes the permissions of a file or directory.', '修改文件或目录的权限。'),
    ('Creates a new symbolic link on the filesystem.', '在文件系统上创建一个新的符号链接。'),
    ('The <code>dst</code> path will be a symbolic link pointing to the <code>original</code> path.', '<code>dst</code> 路径将成为指向 <code>original</code> 路径的符号链接。'),
    ('The dst path will be a symbolic link pointing to the original path.', 'dst 路径将成为指向 original 路径的符号链接。'),
    ('Asynchronously write the entire contents of a buffer to a file.', '异步将缓冲的全部内容写入文件。'),
    ('This function will create a file if it does not exist, and will entirely\nreplace its contents if it does.',
     '若文件不存在，此函数将创建该文件；若已存在，则完全替换其内容。'),
    ('This function will create a file if it does not exist, and will entirely replace its contents if it does.',
     '若文件不存在，此函数将创建该文件；若已存在，则完全替换其内容。'),
    ('Asynchronously reads the directory at the given path and yields <a href="https://doc.rust-lang.org/1.95.0/std/fs/struct.DirEntry.html" title="struct std::fs::DirEntry"><code>DirEntry</code></a> values.',
     '异步读取指定路径的目录并产出 <a href="https://doc.rust-lang.org/1.95.0/std/fs/struct.DirEntry.html" title="struct std::fs::DirEntry"><code>DirEntry</code></a> 值。'),
    ('Reads a symbolic link, returning the file that the link points to.', '读取符号链接，返回链接指向的文件。'),
    ('Returns a future of <code>Option</code>. On success, <code>Some</code> with the directory entries iterator. <code>None</code> if the directory does not exist.',
     '返回 <code>Option</code> 的 Future。成功时为 <code>Some</code>，包含目录条目迭代器；若目录不存在则为 <code>None</code>。'),

    # ===== fs/struct.File =====
    ('Reference to the inner file.', '内部文件的引用。'),
    ('Mutable reference to the inner file.', '内部文件的可变引用。'),
    ('Pinned mutable reference to the inner file.', '内部文件的 pinned 可变引用。'),
    ('Attempts to sync all OS-internal metadata to disk.', '尝试将所有操作系统内部元数据同步到磁盘。'),
    ('This function will attempt to ensure that all in-memory data reaches the\nfilesystem before returning.',
     '此函数将尝试确保所有内存数据在返回前已到达文件系统。'),
    ('This function will attempt to ensure that all in-memory data reaches the filesystem before returning.',
     '此函数将尝试确保所有内存数据在返回前已到达文件系统。'),
    ('This function currently corresponds to the <code>fsync</code> function on Unix\nand the <code>FlushFileBuffers</code> function on Windows.',
     '此函数目前对应于 Unix 上的 <code>fsync</code> 与 Windows 上的 <code>FlushFileBuffers</code>。'),
    ('This function currently corresponds to the fsync function on Unix and the FlushFileBuffers function on Windows.',
     '此函数目前对应于 Unix 上的 fsync 与 Windows 上的 FlushFileBuffers。'),
    ('Get the maximum buffer size for the underlying <code>AsyncRead</code>/<code>AsyncWrite</code> operation.',
     '获取底层 <code>AsyncRead</code>/<code>AsyncWrite</code> 操作的最大缓冲大小。'),
    ('Attempts to open a file in read-only mode.', '尝试以只读模式打开文件。'),
    ('See <a href="struct.OpenOptions.html"><code>OpenOptions</code></a> for more details.', '详见 <a href="struct.OpenOptions.html"><code>OpenOptions</code></a>。'),
    ('See <code>OpenOptions</code> for more details.', '详见 <code>OpenOptions</code>。'),
    ('See OpenOptions for more details.', '详见 OpenOptions。'),
    ('This function will return an error if called from outside of the Tokio\nruntime or if <code>path</code> does not already exist. Other errors may also be\nreturned according to <a href="struct.OpenOptions.html"><code>OpenOptions::open</code></a>.',
     '若在 tokio 运行时外调用此函数，或若 <code>path</code> 不存在，此函数将返回错误。也可能根据 <a href="struct.OpenOptions.html"><code>OpenOptions::open</code></a> 返回其他错误。'),
    ('This function will return an error if called from outside of the Tokio runtime or if path does not already exist. Other errors may also be returned according to OpenOptions::open.',
     '若在 tokio 运行时外调用此函数，或若 path 不存在，此函数将返回错误。也可能根据 OpenOptions::open 返回其他错误。'),
    ('The <a href="trait.AsyncReadExt.html" title="trait tokio::io::AsyncReadExt"><code>read_to_end</code></a> method is defined on the <a href="trait.AsyncReadExt.html" title="trait tokio::io::AsyncReadExt"><code>AsyncReadExt</code></a> trait.',
     '<a href="trait.AsyncReadExt.html" title="trait tokio::io::AsyncReadExt"><code>read_to_end</code></a> 方法定义在 <a href="trait.AsyncReadExt.html" title="trait tokio::io::AsyncReadExt"><code>AsyncReadExt</code></a> 特性上。'),
    ('The <code>read_to_end</code> method is defined on the <code>AsyncReadExt</code> trait.', '<code>read_to_end</code> 方法定义在 <code>AsyncReadExt</code> 特性上。'),
    ('The read_to_end method is defined on the AsyncReadExt trait.', 'read_to_end 方法定义在 AsyncReadExt 特性上。'),
    ('Opens a file in write-only mode.', '以只写模式打开文件。'),
    ('This function will create a file if it does not exist, and will truncate\nit if it does.',
     '若文件不存在，此函数将创建它；若已存在，则将其截断。'),
    ('This function will create a file if it does not exist, and will truncate it if it does.',
     '若文件不存在，此函数将创建它；若已存在，则将其截断。'),
    ('Results in an error if called from outside of the Tokio runtime or if\nthe underlying create call results in an error.',
     '若在 tokio 运行时外调用，或底层 create 调用出错，则返回错误。'),
    ('Results in an error if called from outside of the Tokio runtime or if the underlying create call results in an error.',
     '若在 tokio 运行时外调用，或底层 create 调用出错，则返回错误。'),
    ('The <a href="trait.AsyncWriteExt.html" title="trait tokio::io::AsyncWriteExt"><code>write_all</code></a> method is defined on the <a href="trait.AsyncWriteExt.html" title="trait tokio::io::AsyncWriteExt"><code>AsyncWriteExt</code></a> trait.',
     '<a href="trait.AsyncWriteExt.html" title="trait tokio::io::AsyncWriteExt"><code>write_all</code></a> 方法定义在 <a href="trait.AsyncWriteExt.html" title="trait tokio::io::AsyncWriteExt"><code>AsyncWriteExt</code></a> 特性上。'),
    ('The <code>write_all</code> method is defined on the <code>AsyncWriteExt</code> trait.', '<code>write_all</code> 方法定义在 <code>AsyncWriteExt</code> 特性上。'),
    ('The write_all method is defined on the AsyncWriteExt trait.', 'write_all 方法定义在 AsyncWriteExt 特性上。'),
    ('Opens a file in read-write mode.', '以读写模式打开文件。'),
    ('This function will create a file if it does not exist, and will fail if\nit does.',
     '若文件不存在，此函数将创建它；若已存在，则失败。'),
    ('This function will create a file if it does not exist, and will fail if it does.',
     '若文件不存在，此函数将创建它；若已存在，则失败。'),
    ('Truncates or creates a file in read-write mode.', '以读写模式截断或创建文件。'),
    ('Creates a file in read-write mode.', '以读写模式创建文件。'),
    ('Creates a new file in read-write mode, failing if the file already exists.', '以读写模式创建新文件；若文件已存在则失败。'),
    ('Creates a new file in read-write mode; error if the file already exists.', '以读写模式创建新文件；若文件已存在则报错。'),

    # ===== fs/struct.OpenOptions =====
    ('Options and flags which can be used to configure how a file is opened.', '用于配置文件打开方式的可选项与标志。'),
    ('Creates a blank new set of options ready for configuration.', '创建一组待配置的空白选项。'),
    ('All options are initially set to false.', '所有选项最初均设置为 false。'),
    ('Sets the option for read-access.', '设置读访问选项。'),
    ('Sets the option for write-access.', '设置写访问选项。'),
    ('Sets the option for the append mode.', '设置追加模式选项。'),
    ('Sets the option for truncating an existing file to zero length.', '设置将现有文件截断为零长度的选项。'),
    ('Sets the option for the read-write mode.', '设置读写模式选项。'),
    ('Sets the option for creating a new file.', '设置创建新文件的选项。'),
    ('Sets the option for creating a new file if it does not already exist.', '设置当文件不存在时创建新文件的选项。'),
    ('Sets the option for creating a new file or failing if the file already exists.', '设置创建新文件或若文件已存在则失败的选项。'),
    ('Sets the option for creating a new file or returning an error if the file already exists.', '设置创建新文件或若文件已存在则返回错误的选项。'),
    ('Sets the option for the custom flag.', '设置自定义标志选项。'),
    ('Sets the option for following symbolic links.', '设置跟随符号链接选项。'),

    # ===== fs/struct.ReadDir =====
    ('The <a href="struct.ReadDir.html"><code>ReadDir</code></a> struct is returned by <code>read_dir</code> and allows you to iterate\nover the entries in a directory.',
     '<a href="struct.ReadDir.html"><code>ReadDir</code></a> 结构体由 <code>read_dir</code> 返回，允许你迭代目录中的条目。'),
    ('The <code>ReadDir</code> struct is returned by <code>read_dir</code> and allows you to iterate over the entries in a directory.',
     '<code>ReadDir</code> 结构体由 <code>read_dir</code> 返回，允许你迭代目录中的条目。'),
    ('The ReadDir struct is returned by read_dir and allows you to iterate\nover the entries in a directory.',
     'ReadDir 结构体由 read_dir 返回，允许你迭代目录中的条目。'),
    ('Returns the next entry in the directory stream.', '返回目录流中的下一个条目。'),
    ('Cancel safety: This method is cancellation safe.', '取消安全性：此方法是取消安全的。'),
    ('This method is cancel safe. If you use it as the event in a', '此方法是取消安全的。若你将其作为事件用在'),
    ('Polls for the next directory entry in the stream.', '轮询流中的下一个目录条目。'),
    ('Context is scheduled to receive a wakeup when the next directory entry becomes available.',
     '当下一个目录条目可用时，上下文被调度以接收唤醒。'),
    ('Context is scheduled to receive a wakeup when the next directory entry', '当下一个目录条目可用时，上下文被调度以接收唤醒。'),
    ('This method returns:', '此方法返回：'),
    ('* <code>Poll::Pending</code> if the next directory entry is not yet available.', '* 若下一个目录条目尚未就绪，返回 <code>Poll::Pending</code>。'),
    ('* <code>Poll::Ready(Ok(Some(entry)))</code> if the next directory entry is available.', '* 若下一个目录条目可用，返回 <code>Poll::Ready(Ok(Some(entry)))</code>。'),
    ('* <code>Poll::Ready(Ok(None))</code> if there are no more directory entries in this\nstream.', '* 若此流中再无更多目录条目，返回 <code>Poll::Ready(Ok(None))</code>。'),
    ('* <code>Poll::Ready(Ok(None))</code> if there are no more directory entries in this stream.',
     '* 若此流中再无更多目录条目，返回 <code>Poll::Ready(Ok(None))</code>。'),
    ('* <code>Poll::Ready(Err(error))</code> if an error occurred while reading the next\ndirectory entry.', '* 若读取下一个目录条目时发生错误，返回 <code>Poll::Ready(Err(error))</code>。'),
    ('* <code>Poll::Ready(Err(error))</code> if an error occurred while reading the next directory entry.',
     '* 若读取下一个目录条目时发生错误，返回 <code>Poll::Ready(Err(error))</code>。'),
    ('Note that on multiple calls to <code>poll_next_entry</code>, only the <code>Waker</code> from\nthe <code>Context</code> passed to the most recent call is scheduled to receive a wakeup.',
     '请注意，在多次调用 <code>poll_next_entry</code> 时，只有最近一次调用传入的 <code>Context</code> 中的 <code>Waker</code> 会被调度以接收唤醒。'),
    ('Note that on multiple calls to poll_next_entry, only the Waker from\nthe Context passed to the most recent call is scheduled to receive a wakeup.',
     '请注意，在多次调用 poll_next_entry 时，只有最近一次调用传入的 Context 中的 Waker 会被调度以接收唤醒。'),
    ('When the method returns <code>Poll::Pending</code>, the <code>Waker</code> in the provided\n<code>Context</code> is scheduled to receive a wakeup when more bytes become available.',
     '当此方法返回 <code>Poll::Pending</code> 时，传入的 <code>Context</code> 中的 <code>Waker</code> 被调度以在更多字节可用时接收唤醒。'),
    ('When the method returns Poll::Pending, the Waker in the provided\nContext is scheduled to receive a wakeup when more bytes become',
     '当此方法返回 Poll::Pending 时，传入的 Context 中的 Waker 被调度以在更多字节可用时接收唤醒。'),
    ('If an I/O error is encountered then all bytes read so far will be\ndiscarded.', '若遇到 I/O 错误，到目前为止读取的所有字节都将被丢弃。'),

    # ===== fs/struct.DirEntry =====
    ('Entries returned by the <code>read_dir</code> function.', '由 <code>read_dir</code> 函数返回的条目。'),
    ('Returns the full path to the file that this entry represents.', '返回此条目所代表的文件的完整路径。'),
    ('The full path is created by joining the original path to <code>read_dir</code>\nwith the filename of this entry.',
     '完整路径由原始 <code>read_dir</code> 路径与此条目的文件名拼接而成。'),
    ('The full path is created by joining the original path to read_dir\nwith the filename of this entry.',
     '完整路径由原始 read_dir 路径与此条目的文件名拼接而成。'),
    ('This prints output like:', '输出类似：'),
    ('The exact text, of course, depends on what files you have in ..', '确切的文本当然取决于你在 .. 中有哪些文件。'),
    ('Returns the bare file name of this directory entry without any other\nleading path component.',
     '返回此目录条目的裸文件名（不含任何其他前导路径组件）。'),
    ('Returns the bare file name of this directory entry without any other leading path component.',
     '返回此目录条目的裸文件名（不含任何其他前导路径组件）。'),
    ('Returns the metadata for the file that this entry points at.', '返回此条目所指向文件的元数据。'),
    ('This function will not traverse symlinks if this entry points at a\nsymlink.', '若此条目指向符号链接，此函数不会遍历该符号链接。'),
    ('This function will not traverse symlinks if this entry points at a symlink.', '若此条目指向符号链接，此函数不会遍历该符号链接。'),
    ('On Windows this function is cheap to call (no extra system calls\nneeded), but on Unix platforms this function is the equivalent of\ncalling <code>symlink_metadata</code> on the path.',
     '在 Windows 上，此函数调用开销很小（无需额外的系统调用）；但在 Unix 平台上，此函数等同于对路径调用 <code>symlink_metadata</code>。'),
    ('On Windows this function is cheap to call (no extra system calls needed), but on Unix platforms this function is the equivalent of calling symlink_metadata on the path.',
     '在 Windows 上，此函数调用开销很小（无需额外的系统调用）；但在 Unix 平台上，此函数等同于对路径调用 symlink_metadata。'),
    ('Returns the file type for the file that this entry points at.', '返回此条目所指向文件的文件类型。'),
    ('On Windows and most Unix platforms this function is free (no extra\nsystem calls needed), but some Unix platforms may require the equivalent\ncall to <code>symlink_metadata</code> to learn about the target file type.',
     '在 Windows 与大多数 Unix 平台上，此函数是免费的（无需额外的系统调用），但部分 Unix 平台可能需要等效调用 <code>symlink_metadata</code> 来了解目标文件的类型。'),

    # ===== fs/struct.DirBuilder =====
    ('Options and flags which can be used to configure how a directory is\ncreated.', '用于配置目录创建方式的可选项与标志。'),
    ('Options and flags which can be used to configure how a directory is created.', '用于配置目录创建方式的可选项与标志。'),
    ('Creates a new set of options from an existing value.', '基于现有值创建一组新的选项。'),
    ('Creates a new set of options with default mode/security settings for all platforms and also non-recursive.',
     '创建一组对所有平台使用默认模式/安全设置，且非递归的新选项。'),
    ('Creates a new set of options with default mode/security settings for all\nplatforms and also non-recursive.',
     '创建一组对所有平台使用默认模式/安全设置，且非递归的新选项。'),
    ('Indicates whether to create directories recursively (including all parent directories). Parents that do not exist are created with the same security and permissions settings.',
     '指示是否递归创建目录（包括所有父目录）。不存在的父目录将使用相同的安全与权限设置创建。'),
    ('Indicates whether to create directories recursively (including all parent directories).\nParents that do not exist are created with the same security and permissions settings.',
     '指示是否递归创建目录（包括所有父目录）。不存在的父目录将使用相同的安全与权限设置创建。'),
    ('Sets the option for recursive directory creation.', '设置递归创建目录的选项。'),
    ('It is considered an error if the directory already exists unless\nrecursive mode is enabled.',
     '若目录已存在，则视为错误；除非启用了递归模式。'),
    ('It is considered an error if the directory already exists unless recursive mode is enabled.',
     '若目录已存在，则视为错误；除非启用了递归模式。'),

    # ===== fs/index =====
    ('Asynchronous filesystem operations.', '异步文件系统操作。'),
    ('If you want to use the synchronous version of these functions, use the\n<code>std::fs</code> module.', '若要使用这些函数的同步版本，请使用 <code>std::fs</code> 模块。'),
    ('If you want to use the synchronous version of these functions, use the <code>std::fs</code> module.', '若要使用这些函数的同步版本，请使用 <code>std::fs</code> 模块。'),
    ('This module is only available when the <code>fs</code> feature is enabled.', '此模块仅在启用 <code>fs</code> 特性时可用。'),
    ('Some of the functions in this module are <code>async</code> versions of the\nfunctions in <code>std::fs</code>.', '此模块中部分函数是 <code>std::fs</code> 中函数的 <code>async</code> 版本。'),
    ('Some of the functions in this module are <code>async</code> versions of the functions in <code>std::fs</code>.', '此模块中部分函数是 <code>std::fs</code> 中函数的 <code>async</code> 版本。'),

    # ===== process/struct.Child =====
    ('The <a href="struct.Child.html"><code>Child</code></a> struct allows you to interact with a child process.',
     '<a href="struct.Child.html"><code>Child</code></a> 结构体允许你与子进程交互。'),
    ('The <code>Child</code> struct allows you to interact with a child process.', '<code>Child</code> 结构体允许你与子进程交互。'),
    ('Returns the OS-assigned process identifier associated with this child.', '返回与此子进程关联的、由操作系统分配的进程标识符。'),
    ('A detailed listing of all functions in this trait can be found in the\n<a href="https://doc.rust-lang.org/1.95.0/std/process/struct.Child.html" title="struct std::process::Child">standard library documentation</a>.',
     '本特性所有函数的详细列表可在 <a href="https://doc.rust-lang.org/1.95.0/std/process/struct.Child.html" title="struct std::process::Child">标准库文档</a> 中找到。'),
    ('A detailed listing of all functions in this trait can be found in the <a href="https://doc.rust-lang.org/1.95.0/std/process/struct.Child.html" title="struct std::process::Child">standard library documentation</a>.',
     '本特性所有函数的详细列表可在 <a href="https://doc.rust-lang.org/1.95.0/std/process/struct.Child.html" title="struct std::process::Child">标准库文档</a> 中找到。'),
    ('For this method to be useful, the <code>Child</code> needs to be configured with\n<code>Command::stdout</code>(<code>Stdio::piped</code>()).',
     '要使此方法有用，<code>Child</code> 需要使用 <code>Command::stdout</code>(<code>Stdio::piped</code>()) 进行配置。'),
    ('For this method to be useful, the Child needs to be configured with Command::stdout(Stdio::piped()).',
     '要使此方法有用，Child 需要使用 Command::stdout(Stdio::piped()) 进行配置。'),
    ('For this method to be useful, the <code>Child</code> needs to be configured with\n<code>Command::stderr</code>(<code>Stdio::piped</code>()).',
     '要使此方法有用，<code>Child</code> 需要使用 <code>Command::stderr</code>(<code>Stdio::piped</code>()) 进行配置。'),
    ('For this method to be useful, the Child needs to be configured with Command::stderr(Stdio::piped()).',
     '要使此方法有用，Child 需要使用 Command::stderr(Stdio::piped()) 进行配置。'),
    ('For this method to be useful, the <code>Child</code> needs to be configured with\n<code>Command::stdin</code>(<code>Stdio::piped</code>()).',
     '要使此方法有用，<code>Child</code> 需要使用 <code>Command::stdin</code>(<code>Stdio::piped</code>()) 进行配置。'),
    ('A handle to the process\'s standard input.', '进程标准输入的 handle。'),
    ('A handle to the process\'s standard error output.', '进程标准错误输出的 handle。'),
    ('A handle to the process\'s standard output.', '进程标准输出的 handle。'),
    ('The handle for writing to the child\'s standard input (stdin), if it has been captured.',
     '子进程标准输入 (stdin) 的写入 handle（若已捕获）。'),
    ('The handle for reading from the child\'s standard output (stdout), if it has been captured.',
     '子进程标准输出 (stdout) 的读取 handle（若已捕获）。'),
    ('The handle for reading from the child\'s standard error (stderr), if it has been captured.',
     '子进程标准错误 (stderr) 的读取 handle（若已捕获）。'),
    ('To avoid partially moving the child and thus blocking certain functions on child while using stdin, you should call .into_inner() immediately after writing all data.',
     '为避免部分移动子进程导致在使用 stdin 时某些函数被阻塞，你应该写入所有数据后立即调用 .into_inner()。'),
    ('To avoid partially moving the child and thus blocking certain functions on child while using stdout, you should call .into_inner() immediately after reading all data.',
     '为避免部分移动子进程导致在使用 stdout 时某些函数被阻塞，你应该读取所有数据后立即调用 .into_inner()。'),
    ('To avoid partially moving the child and thus blocking certain functions on child while using stderr, you should call .into_inner() immediately after reading all data.',
     '为避免部分移动子进程导致在使用 stderr 时某些函数被阻塞，你应该读取所有数据后立即调用 .into_inner()。'),
    ('Attempts to force the child to exit, but does not wait for the request to take effect.',
     '尝试强制子进程退出，但不等待请求生效。'),
    ('Extracts the raw handle of the process associated with this child while\nensuring it is closed if the returned <code>OwnedHandle</code> is dropped.',
     '提取与此子进程关联的原始 handle，同时确保在返回的 <code>OwnedHandle</code> 被丢弃时将其关闭。'),
    ('Extracts the raw handle of the process associated with this child while ensuring it is closed if the returned OwnedHandle is dropped.',
     '提取与此子进程关联的原始 handle，同时确保在返回的 OwnedHandle 被丢弃时将其关闭。'),
    ('On Unix systems, this will close any stdin/stdout/stderr handles that were opened via <code>Stdio::piped</code> when the <code>OwnedHandle</code> is dropped.',
     '在 Unix 系统上，当 <code>OwnedHandle</code> 被丢弃时，这将关闭通过 <code>Stdio::piped</code> 打开的所有 stdin/stdout/stderr handle。'),
    ('This method may be used to drop the raw handle without affecting any of the piped stdin/stdout/stderr handles.',
     '此方法可用于丢弃原始 handle 而不影响任何通过管道接出的 stdin/stdout/stderr handle。'),
    ('This function will kill the child process and wait until it has terminated.',
     '此函数将杀死子进程并等待其终止。'),
    ('Important: calling this function is required to prevent a deadlock\nin the case that the child process has captured stdin/stdout/stderr pipes.',
     '重要：在子进程已捕获 stdin/stdout/stderr 管道的场景中，调用此函数对于避免死锁是必需的。'),

    # ===== process/struct.ChildStderr/Stdout/Stdin =====
    ('The standard input stream of a child process.', '子进程的标准输入流。'),
    ('The standard output stream of a child process.', '子进程的标准输出流。'),
    ('The standard error stream of a child process.', '子进程的标准错误流。'),
    ('Creates an asynchronous <code>ChildStderr</code> from a synchronous one.', '从同步 <code>ChildStderr</code> 创建一个异步 <code>ChildStderr</code>。'),
    ('Creates an asynchronous <code>ChildStdout</code> from a synchronous one.', '从同步 <code>ChildStdout</code> 创建一个异步 <code>ChildStdout</code>。'),
    ('Creates an asynchronous <code>ChildStdin</code> from a synchronous one.', '从同步 <code>ChildStdin</code> 创建一个异步 <code>ChildStdin</code>。'),

    # ===== process/struct.Command =====
    ('This structure mimics the API of <code>std::process::Command</code> found in the standard library, but replaces functions that create a process with\nasynchronous equivalents.',
     '此结构体模仿标准库中的 <code>std::process::Command</code> 的 API，但将创建进程的函数替换为其异步等价物。'),
    ('Cheaply convert into a <code>std::process::Command</code>.', '廉价地转换为 <code>std::process::Command</code>。'),
    ('Cheaply convert to a <code>&amp;std::process::Command</code> for places where the type\nfrom the standard library is expected.',
     '在期望标准库类型的位置，可廉价地转换为 <code>&amp;std::process::Command</code>。'),
    ('Cheaply convert to a <code>&amp;mut std::process::Command</code> for places where the\ntype from the standard library is expected.',
     '在期望标准库类型的位置，可廉价地转换为 <code>&amp;mut std::process::Command</code>。'),
    ('Creates a new <code>Command</code> from <code>std::process::Command</code>.',
     '从 <code>std::process::Command</code> 创建一个新的 <code>Command</code>。'),
    ('Creates a new <code>Command</code> from <code>std::process::Command</code>. Other fields are\ninitialized to their default values.',
     '从 <code>std::process::Command</code> 创建一个新的 <code>Command</code>。其他字段初始化为其默认值。'),
    ('Constructs a new <code>Command</code> for launching <code>program</code>.',
     '构造一个用于启动 <code>program</code> 的新 <code>Command</code>。'),
    ('Constructs a new Command for launching the program at', '构造一个用于启动程序的新 Command，'),
    ('The full path to the program can be specified.', '可指定程序的完整路径。'),
    ('Sets the program to be executed when this <code>Command</code> is run.', '设置当此 <code>Command</code> 运行时要执行的程序。'),
    ('Adds an argument to pass to the program.', '添加传递给程序的参数。'),
    ('Adds multiple arguments to pass to the program.', '添加多个传递给程序的参数。'),
    ('Inserts or updates an explicit environment variable mapping.', '插入或更新一个显式的环境变量映射。'),
    ('Removes an explicit environment variable mapping.', '删除一个显式的环境变量映射。'),
    ('If program is not an absolute path, the PATH will be searched in\nthe OS-defined way.',
     '若 program 不是绝对路径，将以操作系统定义的方式搜索 PATH。'),
    ('If program is not an absolute path, the PATH will be searched in the OS-defined way.',
     '若 program 不是绝对路径，将以操作系统定义的方式搜索 PATH。'),
    ('The search path to be used may be controlled by setting the\n<code>PATH</code> environment variable appropriately.',
     '可通过适当设置 <code>PATH</code> 环境变量来控制要使用的搜索路径。'),
    ('The search path to be used may be controlled by setting the PATH environment variable appropriately.',
     '可通过适当设置 PATH 环境变量来控制要使用的搜索路径。'),
    ('Builder methods are provided to change these defaults and\nconfigure other aspects on the <code>Command</code>.',
     '提供了 Builder 方法来修改这些默认值，并配置 <code>Command</code> 的其他方面。'),
    ('To pass multiple arguments see <a href="struct.Command.html#method.args" title="method tokio::process::Command::args"><code>args</code></a>.',
     '若要传递多个参数，请参阅 <a href="struct.Command.html#method.args" title="method tokio::process::Command::args"><code>args</code></a>。'),
    ('To pass multiple arguments see args.', '若要传递多个参数，请参阅 args。'),
    ('Constructs a new <code>Command</code> for launching <code>program</code>.\n\nThe full path to the program can be specified.',
     '构造一个用于启动 <code>program</code> 的新 <code>Command</code>。\n\n可指定程序的完整路径。'),

    # ===== process/index =====
    ('Asynchronous process management.', '异步进程管理。'),
    ('This module is only available when the <code>process</code> feature is enabled.', '此模块仅在启用 <code>process</code> 特性时可用。'),
    ('This crate provides a <a href="struct.Command.html"><code>Command</code></a> type which is a wrapper around <a href="https://doc.rust-lang.org/1.95.0/std/process/struct.Command.html" title="struct std::process::Command"><code>std::process::Command</code></a>.',
     '本 crate 提供 <a href="struct.Command.html"><code>Command</code></a> 类型，是对 <a href="https://doc.rust-lang.org/1.95.0/std/process/struct.Command.html" title="struct std::process::Command"><code>std::process::Command</code></a> 的包装。'),

    # ===== signal/ =====
    ('Asynchronous signal handling.', '异步信号处理。'),
    ('This module is only available when the <code>signal</code> feature is enabled.', '此模块仅在启用 <code>signal</code> 特性时可用。'),
    ('A notification to this process notifies all listeners listening for\nthis event. Moreover, the notifications are coalesced if they aren\'t\nprocessed quickly enough. This means that if two notifications are received\nbefore the first one is processed, the second one will be ignored.',
     '通知此进程将通知所有正在监听此事件的监听器。此外，若通知未能及时处理，通知会被合并。这意味着若在第一个通知处理完之前收到第二个通知，第二个通知将被忽略。'),
    ('A notification to this process notifies all listeners listening for this event. Moreover, the notifications are coalesced if they aren\'t',
     '通知此进程将通知所有正在监听此事件的监听器。此外，若通知未能及时处理，通知会被合并。'),
    ('A notification to this process notifies all receivers for this event. Moreover, the notifications are coalesced if they aren\'t',
     '通知此进程将通知此事件的所有接收者。此外，若通知未能及时处理，通知会被合并。'),
    ('Completes when a "ctrl-c" notification has been received.', '当收到 "ctrl-c" 通知时完成。'),
    ('Creates a future that completes when a "ctrl-c" notification is received.',
     '创建一个在收到 "ctrl-c" 通知时完成的 Future。'),
    ('Use this function to listen for ctrl-c notifications sent to the\nprocess.', '使用此函数监听发送给进程的 ctrl-c 通知。'),
    ('Use this function to listen for ctrl-c notifications sent to the process.', '使用此函数监听发送给进程的 ctrl-c 通知。'),
    ('Representing a listener which receives "ctrl-c" notifications sent to the\nprocess via <code>SetConsoleCtrlHandler</code>. The notifications are\ncoalesced if they are not processed quickly enough.',
     '表示一个监听器，它接收通过 <code>SetConsoleCtrlHandler</code> 发送给进程的 "ctrl-c" 通知。若通知未能快速处理，通知会被合并。'),
    ('Representing a listener which receives "ctrl-c" notifications sent to the process via SetConsoleCtrlHandler. The notifications are coalesced if they are not processed quickly enough.',
     '表示一个监听器，它接收通过 SetConsoleCtrlHandler 发送给进程的 "ctrl-c" 通知。若通知未能快速处理，通知会被合并。'),
    ('The notifications are coalesced if they are not processed quickly\nenough.', '若通知未能快速处理，通知会被合并。'),
    ('The notifications are coalesced if they are not processed quickly enough.', '若通知未能快速处理，通知会被合并。'),
    ('This crate provides async wrappers around <a href="https://doc.rust-lang.org/1.95.0/std/sync/struct.Once.html" title="struct std::sync::Once"><code>std::sync::Once</code></a>, a way to\nrun global initialization code exactly once across all threads in a\nprogram.',
     '本 crate 提供 <a href="https://doc.rust-lang.org/1.95.0/std/sync/struct.Once.html" title="struct std::sync::Once"><code>std::sync::Once</code></a> 的异步包装，用于在整个程序的多个线程中仅执行一次全局初始化代码。'),
    ('Receives the next signal notification event.', '接收下一个信号通知事件。'),
    ('Polls to receive the next signal notification event, outside of an\nasync context.', '在异步上下文之外轮询以接收下一个信号通知事件。'),
    ('Polls to receive the next signal notification event, outside of an async context.', '在异步上下文之外轮询以接收下一个信号通知事件。'),
    ('Although this returns <code>Option&lt;()&gt;</code>, it will never actually return <code>None</code>.\nThis was accidentally exposed and would be a breaking change to be removed.',
     '尽管此函数返回 <code>Option&lt;()&gt;</code>，但实际上永远不会返回 <code>None</code>。\n这是意外暴露的，要删除将是一个破坏性变更。'),
    ('Although this returns Option&lt;()&gt;, it will never actually return None.\nThis was accidentally exposed and would be a breaking change to be removed.',
     '尽管此函数返回 Option&lt;()&gt;，但实际上永远不会返回 None。\n这是意外暴露的，要删除将是一个破坏性变更。'),
    ('Polling from a manually implemented future', '从手动实现的 Future 轮询'),

    # ===== signal/windows/ =====
    ('Windows-specific signal handling.', 'Windows 特有的信号处理。'),
    ('A listener which receives "ctrl-break" notifications sent to the\nprocess via <code>SetConsoleCtrlHandler</code>.',
     '一个监听器，接收通过 <code>SetConsoleCtrlHandler</code> 发送给进程的 "ctrl-break" 通知。'),
    ('A listener which receives "ctrl-break" notifications sent to the process via SetConsoleCtrlHandler.',
     '一个监听器，接收通过 SetConsoleCtrlHandler 发送给进程的 "ctrl-break" 通知。'),
    ('A listener which receives "ctrl-c" notifications sent to the\nprocess via <code>SetConsoleCtrlHandler</code>.',
     '一个监听器，接收通过 <code>SetConsoleCtrlHandler</code> 发送给进程的 "ctrl-c" 通知。'),
    ('A listener which receives "ctrl-close" notifications sent to the\nprocess via <code>SetConsoleCtrlHandler</code>.',
     '一个监听器，接收通过 <code>SetConsoleCtrlHandler</code> 发送给进程的 "ctrl-close" 通知。'),
    ('A listener which receives "ctrl-logoff" notifications sent to the\nprocess via <code>SetConsoleCtrlHandler</code>.',
     '一个监听器，接收通过 <code>SetConsoleCtrlHandler</code> 发送给进程的 "ctrl-logoff" 通知。'),
    ('A listener which receives "ctrl-shutdown" notifications sent to the\nprocess via <code>SetConsoleCtrlHandler</code>.',
     '一个监听器，接收通过 <code>SetConsoleCtrlHandler</code> 发送给进程的 "ctrl-shutdown" 通知。'),
    ('Completes when a "ctrl-break" notification has been received.', '当收到 "ctrl-break" 通知时完成。'),
    ('Completes when a "ctrl-close" notification has been received.', '当收到 "ctrl-close" 通知时完成。'),
    ('Completes when a "ctrl-logoff" notification has been received.', '当收到 "ctrl-logoff" 通知时完成。'),
    ('Completes when a "ctrl-shutdown" notification has been received.', '当收到 "ctrl-shutdown" 通知时完成。'),

    # ===== task/blocking/fn.block_in_place.html =====
    ('This operation is implemented by running the equivalent blocking\noperation on a separate thread pool using <a href="../fn.spawn_blocking.html" title="fn tokio::spawn_blocking"><code>spawn_blocking</code></a>.',
     '此操作通过使用 <a href="../fn.spawn_blocking.html" title="fn tokio::spawn_blocking"><code>spawn_blocking</code></a> 在单独的线程池上运行等效的阻塞操作来实现。'),
    ('This operation is implemented by running the equivalent blocking operation on a separate thread pool using <code>spawn_blocking</code>.',
     '此操作通过使用 <code>spawn_blocking</code> 在单独的线程池上运行等效的阻塞操作来实现。'),
    ('In general, using this method should be avoided.', '通常应避免使用此方法。'),
    ('It is important to keep in mind that this function is not guaranteed to\nbehave the same way as the underlying blocking operation.',
     '请务必注意，此函数的行为不一定与底层阻塞操作完全一致。'),
    ('It is important to keep in mind that this function is not guaranteed to behave the same way as the underlying blocking operation.',
     '请务必注意，此函数的行为不一定与底层阻塞操作完全一致。'),
    ('For example, calling this function on a thread pool thread will not\nsaturate it, as the blocking operation would.',
     '例如，在线程池线程上调用此函数不会像阻塞操作那样饱和线程池。'),
    ('For example, calling this function on a thread pool thread will not saturate it, as the blocking operation would.',
     '例如，在线程池线程上调用此函数不会像阻塞操作那样饱和线程池。'),
    ('Informs the executor that the current task is about to block the current thread, allowing the executor to schedule another task on the current thread.',
     '通知执行器当前任务即将阻塞当前线程，允许执行器在当前线程上调度另一个任务。'),
    ('When a future in the current task blocks the current thread using a synchronous I/O function or other blocking operation, the executor schedules another task to continue running on the current thread.',
     '当当前任务中的 Future 使用同步 I/O 函数或其他阻塞操作阻塞当前线程时，执行器会调度另一个任务以继续在当前线程上运行。'),
    ('In other words, the executor can multiplex tasks on the current thread when one task blocks.',
     '换言之，当某个任务阻塞时，执行器可以在当前线程上多路复用任务。'),
    ('The <code>block_in_place</code> function is used to indicate that the current task is about to block the current thread.',
     '<code>block_in_place</code> 函数用于指示当前任务即将阻塞当前线程。'),

    # ===== io/AsyncBufReadExt.html / AsyncSeekExt.html =====
    ('Asynchronously reads bytes from a source.', '从源异步读取字节。'),
    ('Implemented as an extension trait, adding utility methods to all\n<a href="trait.AsyncBufRead.html" title="trait tokio::io::AsyncBufRead"><code>AsyncBufRead</code></a> types.',
     '作为扩展特性实现，向所有 <a href="trait.AsyncBufRead.html" title="trait tokio::io::AsyncBufRead"><code>AsyncBufRead</code></a> 类型添加工具方法。'),
    ('Implemented as an extension trait, adding utility methods to all <code>AsyncBufRead</code> types.',
     '作为扩展特性实现，向所有 <code>AsyncBufRead</code> 类型添加工具方法。'),
    ('Implemented as an extension trait, adding utility methods to all AsyncBufRead types.',
     '作为扩展特性实现，向所有 AsyncBufRead 类型添加工具方法。'),
    ('Asynchronously seeks to a position in a stream.', '在流中异步定位到指定位置。'),
    ('Implemented as an extension trait, adding utility methods to all\n<a href="trait.AsyncSeek.html" title="trait tokio::io::AsyncSeek"><code>AsyncSeek</code></a> types.',
     '作为扩展特性实现，向所有 <a href="trait.AsyncSeek.html" title="trait tokio::io::AsyncSeek"><code>AsyncSeek</code></a> 类型添加工具方法。'),
    ('Implemented as an extension trait, adding utility methods to all AsyncSeek types.',
     '作为扩展特性实现，向所有 AsyncSeek 类型添加工具方法。'),
    ('Reads bytes from a source.\nImplemented as an extension trait, adding utility methods to all\n<a href="trait.AsyncRead.html" title="trait tokio::io::AsyncRead"><code>AsyncRead</code></a> types. Callers will tend to import this trait instead of\n<a href="trait.AsyncRead.html" title="trait tokio::io::AsyncRead"><code>AsyncRead</code></a>',
     '从源读取字节。\n作为扩展特性实现，向所有 <a href="trait.AsyncRead.html" title="trait tokio::io::AsyncRead"><code>AsyncRead</code></a> 类型添加工具方法。调用者通常会导入本特性而非 <a href="trait.AsyncRead.html" title="trait tokio::io::AsyncRead"><code>AsyncRead</code></a>'),

    # ===== io/fn.split.html / join.html =====
    ('Splits a stream into separate read and write halves.', '将一个流拆分为独立的读、写两半。'),
    ('Joins two streams into one, returning a duplex stream.', '将两个流合并为一个，返回一个双工流。'),

    # ===== io/AsyncReadExt/AsyncWriteExt description =====
    ('Reads bytes from a source. Implemented as an extension trait, adding utility methods to all <code>AsyncRead</code> types.',
     '从源读取字节。作为扩展特性实现，向所有 <code>AsyncRead</code> 类型添加工具方法。'),
    ('Writes bytes to a sink. Implemented as an extension trait, adding utility methods to all <code>AsyncWrite</code> types.',
     '将字节写入汇。作为扩展特性实现，向所有 <code>AsyncWrite</code> 类型添加工具方法。'),
    ('Writes bytes to a sink.', '将字节写入汇。'),

    # ===== io/trait.AsyncRead.html =====
    ('Reads bytes into a buffer.', '将字节读入缓冲。'),
    ('Implementations of <code>poll_read</code> should attempt to read from the\n<code>AsyncRead</code> into the buffer.',
     '<code>poll_read</code> 的实现应尝试从 <code>AsyncRead</code> 读取到缓冲中。'),
    ('If the implementation cannot read any data, an error or <code>Poll::Pending</code> may be returned.',
     '若实现无法读取任何数据，可返回错误或 <code>Poll::Pending</code>。'),
    ('This method is not allowed to return <code>Poll::Ready(Ok(0))</code>. Implementations must instead either return <code>Poll::Ready(Err(...))</code> with a non-zero value or return <code>Poll::Pending</code>.',
     '此方法不允许返回 <code>Poll::Ready(Ok(0))</code>。实现必须改为返回 <code>Poll::Ready(Err(...))</code>（带非零错误值）或返回 <code>Poll::Pending</code>。'),

    # ===== io/util ========
    ('Writes an entire buffer into this writer.', '将整个缓冲写入此写入器。'),
    ('Like <code>write</code>, except that it writes from a slice of buffers.', '与 <code>write</code> 类似，但从一个缓冲切片中写入。'),
    ('Pulls some bytes from this source into the specified buffer, returning\nhow many bytes were read.', '从此源拉取一些字节到指定的缓冲中，返回读取的字节数。'),
    ('Pulls some bytes from this source into the specified buffer, returning how many bytes were read.',
     '从此源拉取一些字节到指定的缓冲中，返回读取的字节数。'),
    ('Reads all bytes into <code>buf</code> until the delimiter byte or EOF is reached.',
     '读取所有字节到 <code>buf</code>，直到遇到分隔字节或 EOF。'),
    ('Reads all bytes into buf until the delimiter byte or EOF is reached.', '读取所有字节到 buf，直到遇到分隔字节或 EOF。'),
    ('Reads all bytes until a newline (the 0xA byte) is reached, and append\nthem to the provided <code>String</code> buffer.',
     '读取所有字节直到遇到换行符（0xA 字节），并将它们追加到提供的 <code>String</code> 缓冲。'),
    ('Reads all bytes until a newline (the 0xA byte) is reached, and append them to the provided <code>String</code> buffer.',
     '读取所有字节直到遇到换行符（0xA 字节），并将它们追加到提供的 <code>String</code> 缓冲。'),
    ('Seek to an offset, in bytes, in the underlying stream.', '在底层流中按字节偏移定位。'),
    ('Seek to the offset, in bytes, in the underlying writer.', '在底层写入器中按字节偏移定位。'),
    ('Seeks to an offset, in bytes, in the underlying reader.', '在底层读取器中按字节偏移定位。'),
    ('Creates a future which will seek an IO object, and then yield the\nnew position.', '创建一个将定位 IO 对象并产出新位置的 Future。'),
    ('Creates a future which will seek an IO object, and then yield the new position.',
     '创建一个将定位 IO 对象并产出新位置的 Future。'),
    ('Creates a future which will return the current seek position from the\nunderlying object.', '创建一个 Future，返回底层对象的当前定位位置。'),
    ('Creates a future which will rewind to the beginning of the stream.', '创建一个将倒回到流开头的 Future。'),
    ('This is convenience method, equivalent to <code>self.seek(SeekFrom::Start(0))</code>.', '这是便捷方法，等价于 <code>self.seek(SeekFrom::Start(0))</code>。'),
    ('This is equivalent to <code>self.seek(SeekFrom::Current(0))</code>.', '这等价于 <code>self.seek(SeekFrom::Current(0))</code>。'),
    ('The position used for <code>seeking</code> with <code>SeekFrom::Current(_)</code> is the\nposition the underlying stream would be at without the effect of the\nbuffer.',
     '使用 <code>SeekFrom::Current(_)</code> 定位时，所用的位置是底层流在不受缓冲影响时所处的位置。'),
    ('See <a href="trait.AsyncSeek.html"><code>AsyncSeek</code></a> for more details.', '详见 <a href="trait.AsyncSeek.html"><code>AsyncSeek</code></a>。'),
    ('See <code>AsyncSeek</code> for more details.', '详见 <code>AsyncSeek</code>。'),
    ('See AsyncSeek for more details.', '详见 AsyncSeek。'),
    ('See <a href="trait.AsyncWrite.html#tymethod.poll_write_vectored" title="tymethod tokio::io::AsyncWrite::poll_write_vectored"><code>AsyncWrite::poll_write_vectored</code></a> for more details.',
     '详见 <a href="trait.AsyncWrite.html#tymethod.poll_write_vectored" title="tymethod tokio::io::AsyncWrite::poll_write_vectored"><code>AsyncWrite::poll_write_vectored</code></a>。'),
    ('See <code>AsyncWrite::poll_write_vectored</code> for more details.', '详见 <code>AsyncWrite::poll_write_vectored</code>。'),
    ('See AsyncWrite::poll_write_vectored for more details.', '详见 AsyncWrite::poll_write_vectored。'),
    ('Seeking always discards the internal buffer, even if the seek position\nfalls within it.',
     '定位总是会丢弃内部缓冲，即使定位位置落在缓冲范围内。'),
    ('Seeking always discards the internal buffer, even if the seek position falls within it.',
     '定位总是会丢弃内部缓冲，即使定位位置落在缓冲范围内。'),
    ('Seeking always writes out the internal buffer before seeking.', '定位前总是会先写出内部缓冲。'),

    # ===== io/trait.AsyncBufRead.html =====
    ('Polls for the next line in the stream.', '轮询流中的下一行。'),
    ('Polls for the next segment in the stream.', '轮询流中的下一段。'),
    ('Polls for the next directory entry in the stream.', '轮询流中的下一个目录条目。'),

    # ===== io/struct.ReadHalf.html docblock =====
    ('The read half of a TCP connection.', 'TCP 连接的读半。'),
    ('This is the half created by <a href="fn.split.html" title="fn tokio::net::split"><code>split</code></a>.', '这是由 <a href="fn.split.html" title="fn tokio::net::split"><code>split</code></a> 创建的半。'),
    ('Allows the use of <code>AsyncRead</code> functionality on the read half.', '允许在读半上使用 <code>AsyncRead</code> 功能。'),
    ('The write half of a TCP connection.', 'TCP 连接的写半。'),
    ('Allows the use of <code>AsyncWrite</code> functionality on the write half.', '允许在写半上使用 <code>AsyncWrite</code> 功能。'),

    # ===== net/ =====
    ('The local address of this TCP stream.', '此 TCP 流的本地地址。'),
    ('The remote address of this TCP stream.', '此 TCP 流的远程地址。'),
    ('The local address of this UDP socket.', '此 UDP 套接字的本地地址。'),
    ('The local address of the UDP socket.', 'UDP 套接字的本地地址。'),
    ('The remote address of the connected peer.', '已连接对端的远程地址。'),
    ('The remote address of this UDP socket.', '此 UDP 套接字的远程地址。'),
    ('The local address of this Unix socket.', '此 Unix 套接字的本地地址。'),
    ('The remote address of this Unix socket.', '此 Unix 套接字的远程地址。'),
    ('A struct used to configure the connection of a TCP listener.', '用于配置 TCP 监听器连接的结构体。'),
    ('A builder for <code>UnixListener</code>.', '<code>UnixListener</code> 的构建器。'),
    ('Connects to a remote address.', '连接到远程地址。'),
    ('The address to connect to.', '要连接的地址。'),
    ('Sets the value of the <code>SO_LINGER</code> option on this socket.', '设置此套接字的 <code>SO_LINGER</code> 选项值。'),
    ('Sets the value of the <code>TCP_NODELAY</code> option on this socket.', '设置此套接字的 <code>TCP_NODELAY</code> 选项值。'),
    ('Sets the value for the <code>IP_TTL</code> option on this socket.', '设置此套接字的 <code>IP_TTL</code> 选项值。'),
    ('Gets the value of the <code>SO_LINGER</code> option on this socket.', '获取此套接字的 <code>SO_LINGER</code> 选项值。'),
    ('Gets the value of the <code>TCP_NODELAY</code> option on this socket.', '获取此套接字的 <code>TCP_NODELAY</code> 选项值。'),
    ('Gets the value of the <code>IP_TTL</code> option on this socket.', '获取此套接字的 <code>IP_TTL</code> 选项值。'),
    ('Gets the local address of this socket.', '获取此套接字的本地地址。'),
    ('Creates a new <code>UnixListener</code> from a <code>std::os::unix::net::UnixListener</code>.',
     '从 <code>std::os::unix::net::UnixListener</code> 创建一个新的 <code>UnixListener</code>。'),
    ('Creates a new <code>UnixStream</code> from a <code>std::os::unix::net::UnixStream</code>.',
     '从 <code>std::os::unix::net::UnixStream</code> 创建一个新的 <code>UnixStream</code>。'),

    # ===== trait.Auto Trait Implementations =====
    ('Unwindsafe', 'UnwindSafe'),
    ('RefUnwindsafe', 'RefUnwindSafe'),
    ('Unpin', 'Unpin'),
    ('Send', 'Send'),
    ('Sync', 'Sync'),
]


def main():
    pairs_b = []
    for en, zh in SENTENCE_PAIRS:
        pairs_b.append((en.encode('utf-8'), zh.encode('utf-8')))

    total_files = 0
    total_replacements = 0
    files_changed = 0

    for root, dirs, files in os.walk(BASE):
        for f in files:
            if not f.endswith('.html'):
                continue
            p = os.path.join(root, f)
            with open(p, 'rb') as fh:
                c = fh.read()
            original = c
            local = 0

            for en_b, zh_b in pairs_b:
                if en_b in c:
                    occurrences = c.count(en_b)
                    c = c.replace(en_b, zh_b)
                    local += occurrences
                en_crlf = en_b.replace(b'\n', b'\r\n')
                zh_crlf = zh_b.replace(b'\n', b'\r\n')
                if en_crlf != en_b and en_crlf in c:
                    occurrences = c.count(en_crlf)
                    c = c.replace(en_crlf, zh_crlf)
                    local += occurrences

            if c != original:
                with open(p, 'wb') as fh:
                    fh.write(c)
                files_changed += 1
                total_replacements += local
            total_files += 1

    print(f'Phase 3: {files_changed}/{total_files} files, {total_replacements} replacements')


if __name__ == '__main__':
    main()