"""Translate remaining 30 untranslated docblocks in quinn/struct.ConnectionId.html."""

import re

PATH = 'D:/Administrator/Documents/Code/rust_doc_all/quinn/struct.ConnectionId.html'

# Use case-by-case translations of first paragraphs
TRANSLATIONS = [
    # as_ascii
    ('<p>If this slice <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.is_ascii" title="method slice::is_ascii"><code>is_ascii</code></a>, returns it as a slice of\n<a href="https://doc.rust-lang.org/1.95.0/core/ascii/ascii_char/enum.AsciiChar.html" title="enum core::ascii::ascii_char::AsciiChar">ASCII characters</a>, otherwise returns <code>None</code>.</p>',
     '<p>若此切片 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.is_ascii" title="method slice::is_ascii"><code>is_ascii</code></a>，则将其作为 <a href="https://doc.rust-lang.org/1.95.0/core/ascii/ascii_char/enum.AsciiChar.html" title="enum core::ascii::ascii_char::AsciiChar">ASCII 字符</a> 的切片返回；否则返回 <code>None</code>。</p>'),
    # get_mut
    ('<p>Returns a mutable reference to an element or subslice depending on the\ntype of index (see <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.get" title="method slice::get"><code>get</code></a>) or <code>None</code> if the index is out of bounds.</p>',
     '<p>依据索引类型返回对一个元素或子切片的可变引用（详见 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.get" title="method slice::get"><code>get</code></a>）；若索引越界则返回 <code>None</code>。</p>'),
    # windows
    ('<p>Returns an iterator over all contiguous windows of length\n<code>size</code>. The windows overlap. If the slice is shorter than\n<code>size</code>, the iterator returns no values.</p>\n<h5 id="panics-1"><a class="doc-anchor" href="#panics-1">§</a>Panics</h5>\n<p>Panics if <code>size</code> is zero.</p>',
     '<p>返回一个迭代器，遍历长度为 <code>size</code> 的所有连续窗口。各窗口相互重叠。若切片短于 <code>size</code>，则迭代器不产生任何元素。</p>\n<h5 id="panics-1"><a class="doc-anchor" href="#panics-1">§</a>Panics</h5>\n<p>若 <code>size</code> 为零则 panic。</p>'),
    # chunks
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the\nbeginning of the slice.</p>\n<p>The chunks are slices and do not overlap. If <code>chunk_size</code> does not divide the length of the\nslice, then the last chunk will not have length <code>chunk_size</code>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact" title="method slice::chunks_exact"><code>chunks_exact</code></a> for a variant of this iterator that returns chunks of always exactly\n<code>chunk_size</code> elements, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks" title="method slice::rchunks"><code>rchunks</code></a> for the same iterator but starting at the end of the\nslice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks" title="method slice::as_chunks"><code>as_chunks</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-2"><a class="doc-anchor" href="#panics-2">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片开头开始。</p>\n<p>各块为切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，最后一块的长度将不等于 <code>chunk_size</code>。</p>\n<p>若希望迭代器总是返回长度恰为 <code>chunk_size</code> 的块，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact" title="method slice::chunks_exact"><code>chunks_exact</code></a>；若希望从切片末尾开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks" title="method slice::rchunks"><code>rchunks</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks" title="method slice::as_chunks"><code>as_chunks</code></a>，它会返回长度恰为该常量的数组引用，而非切片引用。</p>\n<h5 id="panics-2"><a class="doc-anchor" href="#panics-2">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # chunks_mut
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the\nbeginning of the slice.</p>\n<p>The chunks are mutable slices, and do not overlap. If <code>chunk_size</code> does not divide the\nlength of the slice, then the last chunk will not have length <code>chunk_size</code>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact_mut" title="method slice::chunks_exact_mut"><code>chunks_exact_mut</code></a> for a variant of this iterator that returns chunks of always\nexactly <code>chunk_size</code> elements, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_mut" title="method slice::rchunks_mut"><code>rchunks_mut</code></a> for the same iterator but starting at\nthe end of the slice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks_mut" title="method slice::as_chunks_mut"><code>as_chunks_mut</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-3"><a class="doc-anchor" href="#panics-3">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片开头开始。</p>\n<p>各块为可变切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，最后一块的长度将不等于 <code>chunk_size</code>。</p>\n<p>若希望迭代器总是返回长度恰为 <code>chunk_size</code> 的块，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact_mut" title="method slice::chunks_exact_mut"><code>chunks_exact_mut</code></a>；若希望从切片末尾开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_mut" title="method slice::rchunks_mut"><code>rchunks_mut</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks_mut" title="method slice::as_chunks_mut"><code>as_chunks_mut</code></a>，它会返回长度恰为该常量的数组引用，而非切片引用。</p>\n<h5 id="panics-3"><a class="doc-anchor" href="#panics-3">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # chunks_exact
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the\nbeginning of the slice.</p>\n<p>The chunks are slices and do not overlap. If <code>chunk_size</code> does not divide the length of the\nslice, then the last up to <code>chunk_size-1</code> elements will be omitted and can be retrieved\nfrom the <code>remainder</code> function of the iterator.</p>\n<p>Due to each chunk having exactly <code>chunk_size</code> elements, the compiler can often optimize the\nresulting code better than in the case of <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks" title="method slice::chunks"><code>chunks</code></a>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks" title="method slice::chunks"><code>chunks</code></a> for a variant of this iterator that also returns the remainder as a smaller\nchunk, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact" title="method slice::rchunks_exact"><code>rchunks_exact</code></a> for the same iterator but starting at the end of the slice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks" title="method slice::as_chunks"><code>as_chunks</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-4"><a class="doc-anchor" href="#panics-4">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片开头开始。</p>\n<p>各块为切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，末尾最多 <code>chunk_size-1</code> 个元素将被略过，可通过迭代器的 <code>remainder</code> 函数取回。</p>\n<p>由于每块恰好包含 <code>chunk_size</code> 个元素，编译器通常能比 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks" title="method slice::chunks"><code>chunks</code></a> 更优化所生成的代码。</p>\n<p>若希望迭代器将剩余元素也作为较小的块返回，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks" title="method slice::chunks"><code>chunks</code></a>；若希望从切片末尾开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact" title="method slice::rchunks_exact"><code>rchunks_exact</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks" title="method slice::as_chunks"><code>as_chunks</code></a>。</p>\n<h5 id="panics-4"><a class="doc-anchor" href="#panics-4">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # chunks_exact_mut
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the\nbeginning of the slice.</p>\n<p>The chunks are mutable slices, and do not overlap. If <code>chunk_size</code> does not divide the\nlength of the slice, then the last up to <code>chunk_size-1</code> elements will be omitted and can be\nretrieved from the <code>into_remainder</code> function of the iterator.</p>\n<p>Due to each chunk having exactly <code>chunk_size</code> elements, the compiler can often optimize the\nresulting code better than in the case of <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_mut" title="method slice::chunks_mut"><code>chunks_mut</code></a>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_mut" title="method slice::chunks_mut"><code>chunks_mut</code></a> for a variant of this iterator that also returns the remainder as a\nsmaller chunk, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact_mut" title="method slice::rchunks_exact_mut"><code>rchunks_exact_mut</code></a> for the same iterator but starting at the end of\nthe slice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks_mut" title="method slice::as_chunks_mut"><code>as_chunks_mut</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-5"><a class="doc-anchor" href="#panics-5">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片开头开始。</p>\n<p>各块为可变切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，末尾最多 <code>chunk_size-1</code> 个元素将被略过，可通过迭代器的 <code>into_remainder</code> 函数取回。</p>\n<p>由于每块恰好包含 <code>chunk_size</code> 个元素，编译器通常能比 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_mut" title="method slice::chunks_mut"><code>chunks_mut</code></a> 更优化所生成的代码。</p>\n<p>若希望迭代器将剩余元素也作为较小的块返回，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_mut" title="method slice::chunks_mut"><code>chunks_mut</code></a>；若希望从切片末尾开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact_mut" title="method slice::rchunks_exact_mut"><code>rchunks_exact_mut</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_chunks_mut" title="method slice::as_chunks_mut"><code>as_chunks_mut</code></a>。</p>\n<h5 id="panics-5"><a class="doc-anchor" href="#panics-5">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # rchunks
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the end\nof the slice.</p>\n<p>The chunks are slices and do not overlap. If <code>chunk_size</code> does not divide the length of the\nslice, then the last chunk will not have length <code>chunk_size</code>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact" title="method slice::rchunks_exact"><code>rchunks_exact</code></a> for a variant of this iterator that returns chunks of always exactly\n<code>chunk_size</code> elements, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks" title="method slice::chunks"><code>chunks</code></a> for the same iterator but starting at the beginning\nof the slice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks" title="method slice::as_rchunks"><code>as_rchunks</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-11"><a class="doc-anchor" href="#panics-11">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片末尾开始。</p>\n<p>各块为切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，最后一块的长度将不等于 <code>chunk_size</code>。</p>\n<p>若希望迭代器总是返回长度恰为 <code>chunk_size</code> 的块，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact" title="method slice::rchunks_exact"><code>rchunks_exact</code></a>；若希望从切片开头开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks" title="method slice::chunks"><code>chunks</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks" title="method slice::as_rchunks"><code>as_rchunks</code></a>。</p>\n<h5 id="panics-11"><a class="doc-anchor" href="#panics-11">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # rchunks_mut
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the end\nof the slice.</p>\n<p>The chunks are mutable slices, and do not overlap. If <code>chunk_size</code> does not divide the\nlength of the slice, then the last chunk will not have length <code>chunk_size</code>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact_mut" title="method slice::rchunks_exact_mut"><code>rchunks_exact_mut</code></a> for a variant of this iterator that returns chunks of always\nexactly <code>chunk_size</code> elements, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_mut" title="method slice::chunks_mut"><code>chunks_mut</code></a> for the same iterator but starting at the\nbeginning of the slice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks_mut" title="method slice::as_rchunks_mut"><code>as_rchunks_mut</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-12"><a class="doc-anchor" href="#panics-12">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片末尾开始。</p>\n<p>各块为可变切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，最后一块的长度将不等于 <code>chunk_size</code>。</p>\n<p>若希望迭代器总是返回长度恰为 <code>chunk_size</code> 的块，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_exact_mut" title="method slice::rchunks_exact_mut"><code>rchunks_exact_mut</code></a>；若希望从切片开头开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_mut" title="method slice::chunks_mut"><code>chunks_mut</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks_mut" title="method slice::as_rchunks_mut"><code>as_rchunks_mut</code></a>。</p>\n<h5 id="panics-12"><a class="doc-anchor" href="#panics-12">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # rchunks_exact
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the\nend of the slice.</p>\n<p>The chunks are slices and do not overlap. If <code>chunk_size</code> does not divide the length of the\nslice, then the last up to <code>chunk_size-1</code> elements will be omitted and can be retrieved\nfrom the <code>remainder</code> function of the iterator.</p>\n<p>Due to each chunk having exactly <code>chunk_size</code> elements, the compiler can often optimize the\nresulting code better than in the case of <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks" title="method slice::rchunks"><code>rchunks</code></a>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks" title="method slice::rchunks"><code>rchunks</code></a> for a variant of this iterator that also returns the remainder as a smaller\nchunk, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact" title="method slice::chunks_exact"><code>chunks_exact</code></a> for the same iterator but starting at the beginning of the\nslice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks" title="method slice::as_rchunks"><code>as_rchunks</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-13"><a class="doc-anchor" href="#panics-13">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片末尾开始。</p>\n<p>各块为切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，开头最多 <code>chunk_size-1</code> 个元素将被略过，可通过迭代器的 <code>remainder</code> 函数取回。</p>\n<p>由于每块恰好包含 <code>chunk_size</code> 个元素，编译器通常能比 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks" title="method slice::rchunks"><code>rchunks</code></a> 更优化所生成的代码。</p>\n<p>若希望迭代器将剩余元素也作为较小的块返回，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks" title="method slice::rchunks"><code>rchunks</code></a>；若希望从切片开头开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact" title="method slice::chunks_exact"><code>chunks_exact</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks" title="method slice::as_rchunks"><code>as_rchunks</code></a>。</p>\n<h5 id="panics-13"><a class="doc-anchor" href="#panics-13">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # rchunks_exact_mut
    ('<p>Returns an iterator over <code>chunk_size</code> elements of the slice at a time, starting at the end\nof the slice.</p>\n<p>The chunks are mutable slices, and do not overlap. If <code>chunk_size</code> does not divide the\nlength of the slice, then the last up to <code>chunk_size-1</code> elements will be omitted and can be\nretrieved from the <code>into_remainder</code> function of the iterator.</p>\n<p>Due to each chunk having exactly <code>chunk_size</code> elements, the compiler can often optimize the\nresulting code better than in the case of <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_mut" title="method slice::rchunks_mut"><code>rchunks_mut</code></a>.</p>\n<p>See <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_mut" title="method slice::rchunks_mut"><code>rchunks_mut</code></a> for a variant of this iterator that also returns the remainder as a smaller\nchunk, and <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact_mut" title="method slice::chunks_exact_mut"><code>chunks_exact_mut</code></a> for the same iterator but starting at the beginning\nof the slice.</p>\n<p>If your <code>chunk_size</code> is a constant, consider using <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks_mut" title="method slice::as_rchunks_mut"><code>as_rchunks_mut</code></a> instead, which will\ngive references to arrays of exactly that length, rather than slices.</p>\n<h5 id="panics-14"><a class="doc-anchor" href="#panics-14">§</a>Panics</h5>\n<p>Panics if <code>chunk_size</code> is zero.</p>',
     '<p>返回一个迭代器，每次遍历切片的 <code>chunk_size</code> 个元素，从切片末尾开始。</p>\n<p>各块为可变切片且互不重叠。若 <code>chunk_size</code> 不能整除切片长度，开头最多 <code>chunk_size-1</code> 个元素将被略过，可通过迭代器的 <code>into_remainder</code> 函数取回。</p>\n<p>由于每块恰好包含 <code>chunk_size</code> 个元素，编译器通常能比 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_mut" title="method slice::rchunks_mut"><code>rchunks_mut</code></a> 更优化所生成的代码。</p>\n<p>若希望迭代器将剩余元素也作为较小的块返回，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.rchunks_mut" title="method slice::rchunks_mut"><code>rchunks_mut</code></a>；若希望从切片开头开始，请参阅 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.chunks_exact_mut" title="method slice::chunks_exact_mut"><code>chunks_exact_mut</code></a>。</p>\n<p>若 <code>chunk_size</code> 为编译期常量，建议改用 <a href="https://doc.rust-lang.org/1.95.0/std/primitive.slice.html#method.as_rchunks_mut" title="method slice::as_rchunks_mut"><code>as_rchunks_mut</code></a>。</p>\n<h5 id="panics-14"><a class="doc-anchor" href="#panics-14">§</a>Panics</h5>\n<p>若 <code>chunk_size</code> 为零则 panic。</p>'),
    # split_at_checked
    ('<p>Divides one slice into two at an index, returning <code>None</code> if the slice is\ntoo short.</p>\n<p>If <code>mid ≤ len</code> returns a pair of slices where the first will contain all\nindices from <code>[0, mid)</code> (excluding the index <code>mid</code> itself) and the\nsecond will contain all indices from <code>[mid, len)</code> (excluding the index\n<code>len</code> itself).</p>\n<p>Otherwise, if <code>mid &gt; len</code>, returns <code>None</code>.</p>',
     '<p>在某个索引处将切片一分为二；若切片过短则返回 <code>None</code>。</p>\n<p>若 <code>mid ≤ len</code>，返回一对切片，其中第一段包含区间 <code>[0, mid)</code> 中的所有索引（不含 <code>mid</code> 本身），第二段包含 <code>[mid, len)</code> 中的所有索引（不含 <code>len</code> 本身）。</p>\n<p>否则，若 <code>mid &gt; len</code>，返回 <code>None</code>。</p>'),
    # split_at_mut_checked
    ('<p>Divides one mutable slice into two at an index, returning <code>None</code> if the\nslice is too short.</p>\n<p>If <code>mid ≤ len</code> returns a pair of slices where the first will contain all\nindices from <code>[0, mid)</code> (excluding the index <code>mid</code> itself) and the\nsecond will contain all indices from <code>[mid, len)</code> (excluding the index\n<code>len</code> itself).</p>\n<p>Otherwise, if <code>mid &gt; len</code>, returns <code>None</code>.</p>',
     '<p>在某个索引处将可变切片一分为二；若切片过短则返回 <code>None</code>。</p>\n<p>若 <code>mid ≤ len</code>，返回一对切片，其中第一段包含区间 <code>[0, mid)</code> 中的所有索引（不含 <code>mid</code> 本身），第二段包含 <code>[mid, len)</code> 中的所有索引（不含 <code>len</code> 本身）。</p>\n<p>否则，若 <code>mid &gt; len</code>，返回 <code>None</code>。</p>'),
    # split
    ('<p>Returns an iterator over subslices separated by elements that match\n<code>pred</code>. The matched element is contained in the end of the previous\nsubslice as a terminator.</p>',
     '<p>返回一个迭代器，遍历由满足 <code>pred</code> 的元素分隔开的子切片。匹配元素作为终止符包含在前一个子切片的末尾。</p>'),
    # split_inclusive_mut
    ('<p>Returns an iterator over mutable subslices separated by elements that\nmatch <code>pred</code>. The matched element is contained in the previous\nsubslice as a terminator.</p>',
     '<p>返回一个迭代器，遍历由满足 <code>pred</code> 的元素分隔开的可变子切片。匹配元素作为终止符包含在前一个子切片中。</p>'),
    # rsplit
    ('<p>Returns an iterator over subslices separated by elements that match\n<code>pred</code>, starting at the end of the slice and working backwards.\nThe matched element is not contained in the subslices.</p>',
     '<p>返回一个迭代器，从切片末尾开始向前遍历由满足 <code>pred</code> 的元素分隔开的子切片。匹配元素本身不包含在子切片中。</p>'),
    # rsplit_mut
    ('<p>Returns an iterator over mutable subslices separated by elements that\nmatch <code>pred</code>, starting at the end of the slice and working\nbackwards. The matched element is not contained in the subslices.</p>',
     '<p>返回一个迭代器，从切片末尾开始向前遍历由满足 <code>pred</code> 的元素分隔开的可变子切片。匹配元素本身不包含在子切片中。</p>'),
    # rotate_left
    ('<p>Rotates the slice in-place such that the first <code>mid</code> elements of the\nslice move to the end while the last <code>self.len() - mid</code> elements move to\nthe front.</p>\n<p>After calling <code>rotate_left</code>, the element previously at index <code>mid</code> will\nbecome the first element in the slice.</p>\n<h5 id="panics-26"><a class="doc-anchor" href="#panics-26">§</a>Panics</h5>\n<p>This function will panic if <code>mid</code> is greater than the length of the\nslice. Note that <code>mid == self.len()</code> does <em>not</em> panic and is a no-op\nrotation.</p>\n<h5 id="complexity"><a class="doc-anchor" href="#complexity">§</a>Complexity</h5>\n<p>Takes linear (in <code>self.len()</code>) time.</p>',
     '<p>将切片原地旋转，使得切片开头的 <code>mid</code> 个元素移到末尾，末尾的 <code>self.len() - mid</code> 个元素移到开头。</p>\n<p>调用 <code>rotate_left</code> 后，原本索引为 <code>mid</code> 的元素将成为切片中的第一个元素。</p>\n<h5 id="panics-26"><a class="doc-anchor" href="#panics-26">§</a>Panics</h5>\n<p>若 <code>mid</code> 大于切片长度则 panic。注意 <code>mid == self.len()</code> 不会 panic，是一次空操作旋转。</p>\n<h5 id="complexity"><a class="doc-anchor" href="#complexity">§</a>复杂度</h5>\n<p>耗时与 <code>self.len()</code> 成线性。</p>'),
    # rotate_right
    ('<p>Rotates the slice in-place such that the first <code>self.len() - k</code>\nelements of the slice move to the end while the last <code>k</code> elements move\nto the front.</p>\n<p>After calling <code>rotate_right</code>, the element previously at index\n<code>self.len() - k</code> will become the first element in the slice.</p>\n<h5 id="panics-27"><a class="doc-anchor" href="#panics-27">§</a>Panics</h5>\n<p>This function will panic if <code>k</code> is greater than the length of the\nslice. Note that <code>k == self.len()</code> does <em>not</em> panic and is a no-op\nrotation.</p>\n<h5 id="complexity-1"><a class="doc-anchor" href="#complexity-1">§</a>Complexity</h5>\n<p>Takes linear (in <code>self.len()</code>) time.</p>',
     '<p>将切片原地旋转，使得切片开头的 <code>self.len() - k</code> 个元素移到末尾，末尾的 <code>k</code> 个元素移到开头。</p>\n<p>调用 <code>rotate_right</code> 后，原本索引为 <code>self.len() - k</code> 的元素将成为切片中的第一个元素。</p>\n<h5 id="panics-27"><a class="doc-anchor" href="#panics-27">§</a>Panics</h5>\n<p>若 <code>k</code> 大于切片长度则 panic。注意 <code>k == self.len()</code> 不会 panic，是一次空操作旋转。</p>\n<h5 id="complexity-1"><a class="doc-anchor" href="#complexity-1">§</a>复杂度</h5>\n<p>耗时与 <code>self.len()</code> 成线性。</p>'),
    # shift_left
    ('<p>Moves the elements of this slice <code>N</code> places to the left, returning the ones\nthat “fall off” the front, and putting <code>inserted</code> at the end.</p>\n<p>Equivalently, you can think of concatenating <code>self</code> and <code>inserted</code> into one\nlong sequence, then returning the left-most <code>N</code> items and the rest into <code>self</code>:</p>',
     '<p>将切片中的元素向左移动 <code>N</code> 个位置，返回从开头“掉出”的元素，并将 <code>inserted</code> 放到末尾。</p>\n<p>等价地，你可以把 <code>self</code> 与 <code>inserted</code> 串接成一个长序列，然后把最左侧的 <code>N</code> 个返回，其余放回 <code>self</code>：</p>'),
    # shift_right
    ('<p>Moves the elements of this slice <code>N</code> places to the right, returning the ones\nthat “fall off” the back, and putting <code>inserted</code> at the beginning.</p>\n<p>Equivalently, you can think of concatenating <code>inserted</code> and <code>self</code> into one\nlong sequence, then returning the right-most <code>N</code> items and the rest into <code>self</code>:</p>',
     '<p>将切片中的元素向右移动 <code>N</code> 个位置，返回从末尾“掉出”的元素，并将 <code>inserted</code> 放到开头。</p>\n<p>等价地，你可以把 <code>inserted</code> 与 <code>self</code> 串接成一个长序列，然后把最右侧的 <code>N</code> 个返回，其余放回 <code>self</code>：</p>'),
]


def main():
    with open(PATH, 'r', encoding='utf-8') as f:
        c = f.read()

    found = 0
    missed = []
    for old, new in TRANSLATIONS:
        if old in c:
            c = c.replace(old, new)
            found += 1
        else:
            missed.append(old[:80])

    with open(PATH, 'w', encoding='utf-8') as f:
        f.write(c)

    cjk = re.findall(r'[一-鿿]', c)
    print(f'Found: {found}/{len(TRANSLATIONS)} docblocks')
    print(f'CJK: {len(cjk)}')
    if missed:
        print('Missed docblocks:')
        for m in missed:
            print(f'  {m!r}')


if __name__ == '__main__':
    main()
