"""Translate 4 untranslated docblocks in quinn/trait.ConnectionIdGenerator.html."""

import re

PATH = 'D:/Administrator/Documents/Code/rust_doc_all/quinn/trait.ConnectionIdGenerator.html'

TRANSLATIONS = [
    ('<p>Generates a new CID</p>\n<p>Connection IDs MUST NOT contain any information that can be used by\nan external observer (that is, one that does not cooperate with the\nissuer) to correlate them with other connection IDs for the same\nconnection. They MUST have high entropy, e.g. due to encrypted data\nor cryptographic-grade random data.</p>',
     '<p>生成新的 CID</p>\n<p>连接 ID 不得包含任何可被外部观察者（即未与颁发方协作的一方）用来将其与同一连接的其他连接 ID 进行关联的信息。\n连接 ID 必须具有高熵，例如由加密数据或密码学级别的随机数据生成。</p>'),
    ('<p>Returns the length of a CID for connections created by this generator</p>',
     '<p>返回由该生成器创建的连接的 CID 长度</p>'),
    ('<p>Returns the lifetime of generated Connection IDs</p>\n<p>Connection IDs will be retired after the returned <code>Duration</code>, if any. Assumed to be constant.</p>',
     '<p>返回所生成连接 ID 的生命周期</p>\n<p>连接 ID 在经过返回的 <code>Duration</code>（如有）后将退役。假定该值是恒定的。</p>'),
    ('<p>Quickly determine whether <code>cid</code> could have been generated by this generator</p>\n<p>False positives are permitted, but increase the cost of handling invalid packets.</p>',
     '<p>快速判断 <code>cid</code> 是否可能由该生成器生成</p>\n<p>允许存在误报，但会增加处理无效包的成本。</p>'),
]


def main():
    with open(PATH, 'r', encoding='utf-8') as f:
        c = f.read()

    found = 0
    missed = []
    for old, new in TRANSLATIONS:
        if old in c:
            c = c.replace(old, new)
            found += 1
        else:
            missed.append(old[:80])

    with open(PATH, 'w', encoding='utf-8') as f:
        f.write(c)

    cjk = re.findall(r'[一-鿿]', c)
    print(f'Found: {found}/{len(TRANSLATIONS)} docblocks')
    print(f'CJK: {len(cjk)}')
    if missed:
        print('Missed docblocks:')
        for m in missed:
            print(f'  {m!r}')


if __name__ == '__main__':
    main()